project:
  type: website
  output-dir: docs

website:
  title: "Mario Arce Acosta"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Interactive Analytics
      - text: "Research"       # The Header Name (e.g., 'Research', 'Portfolio')
        menu:
        - href: research.qmd
          text: ML Research
        - text: "---"  # <--- This creates a horizontal divider line
        - href: leading_model.qmd
          text: ML Leading Model
      - href: media/_Academic__Mario_CV.pdf
        text: CV

format:
  html:
    theme: 
      dark: solar
      light: minty
    css: styles.css
    toc: true

editor: visual

