project:
  type: website
  output-dir: docs

website:
  title: "Mario Arce Acosta"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Interactive Analytics
      - href: research.qmd
        text: Research
      - href: media/_Academic__Mario_CV.pdf
        text: CV

format:
  html:
    theme: 
      dark: solar
      light: minty
    css: styles.css
    toc: true

editor: visual

