project:
  type: website
  output-dir: docs

website:
  title: "Mario Arce Acosta"
  navbar:
    right:
      - href: index.qmd
        text: Home

      - text: "Research"       # The Header Name (e.g., 'Research', 'Portfolio')
        menu:
        - href: dashboard.qmd
          text: (In Progress) Interactive Descriptive Statistics
        - href: research.qmd
          text: ML Model Comparisons
        - href: leading_model.qmd
          text: Leading Model Performance
        - href: stata_analysis.qmd
          text: Regression Analysis
          
      - text: "Other Work"       # The Header Name (e.g., 'Research', 'Portfolio')
        menu:
        - href: projects.qmd
          text: Portfolio
        - href: presentations.qmd
          text: Conferences & Presentations
        - href: freelance.qmd
          text: Freelancing
        
      - href: files/_Academic__Mario_CV.pdf
        text: CV

format:
  html:
    theme: 
      dark: solar
      light: minty
    css: styles.css
    toc: true
filters:
  - lightbox
lightbox: auto  # Automatically makes images zoomable

editor: visual

